title: Nerding Club
email: someone@nerding.club
description: Just a sute for testing out the functionality of GitHub Pages and customer domains.
twitter_username: vstaropoli
github_username: thevinnie
theme: jekyll-theme-hacker
